### ISSUE TITLE
TLS Mosquitto WebSockets are broken on Firefox

### ISSUE THREAD

**Issue by nm17** [danarrib/BulletGCSS#45]
Firefox refuses to connect to wss protocol even with a valid CA certificate, even though it works on Chromium 88.0.4324.182.
Firefox version: 86.0

Bisecting Firefox and Mosquitto resulted in nothing.

## Current status on the browser tests
| Certificate Type | Firefox 86 | Chromium 88 |
|-|-|-|
| Self Signed (v1.5.7) | Works according to @stronnag | Should work |
| Let's encrypt (v1.5.7) | Doesn't work | Should work |
| Self Signed (v2.0.7) | Not tested? | Most likely works |
| Let's Encrypt (v2.0.7) | Doesn't work | Works |

**Comment by stronnag** [comment]
| Certificate type | FF 86 | Cr 88 |
| -------------------- | -------- | ------- |
| Self signed (v.1.5.7) | Y | Y |
| Let's Encrypt (v.1.5.7) | not tested| not tested |
| Self signed (v.2.0.7) | N | Y |
| Let's Encrypt (v.1.5.7) | N | Y |

All the certificate / versions also work with clients based the Paho Go library.
Looks like a Firefox issue to me.

**Comment by stronnag** [comment]
@nm17 Please try
* about:config
* set `network.http.spdy.websockets` to `false`

works for me :)

**Comment by nm17** [comment]
@stronnag yep, can confirm it fixes everything

**Comment by stronnag** [comment]
cool. maybe I'll write a wiki doc on self hosting at some time, maybe tomorrow.

**Comment by danarrib** [comment]
Congrats guys. I'll add this note to the docs as well.

**Comment by nm17** [comment]
@danarrib did you add it?

**Comment by danarrib** [comment]
@nm17 I just added the following note:

> **Note for Mozilla Firefox users with self-hosted Mosquitto MQTT Broker**
> Mozilla Firefox sometimes has problems to validate the SSL certificate. To fix this:
> 1. Open Firefox and type `about:config` on it's address bar
> 2. Find the key `network.http.spdy.websockets` and set it to `false`
> 3. Restart Firefox

To this page: https://github.com/danarrib/BulletGCSS/wiki/User-Interface

The page about Self hosted Mosquitto already has this note, as Jonathan wrote it.
https://github.com/danarrib/BulletGCSS/wiki/Self-Hosting-a-MQTT-server--(broker)

**Comment by nm17** [comment]
Great, I guess I'll close this issue now
